#!/bin/bash

# Read config file
. config/config.sh
# Get values
. data/configparser.sh

echo -e "\nUmVirt LFS Customizer configuration"
echo -e "-------------------------------------\n"
echo "Target partition: $LFS_PARTITION"
echo "Target architecture: $LFS_TARGET_ARCH"
echo "Target init system: $LFS_TARGET_INIT"
echo
echo "Local repository: $LOCALREPO"
echo
echo "SourcesDisk: $SOURCESDISK"
echo "SourcesDisk formatting: $FORMATSOURCESDISK"
echo
echo "Zerofill: $ZEROFILL"
echo
if [[ $LFS_MBR = "YES" ]]
then
echo "GRUB MBR bootloader installation settings"
echo
echo "Running disk number: $LFS_RUNNING_DISK_NUMBER"
echo "Running partition number: $LFS_RUNNING_PARTITION_NUMBER"
echo "Target disk to install MBR: $LFS_DISK"
fi
